dist: trusty
sudo: false

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev
    - cppcheck

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - OPTS="--enable-parser-generation $OPTS"
  - OPTS="--without-curl $OPTS"
  - OPTS="--without-yajl $OPTS"
  - OPTS="--without-geoip $OPTS"
  - OPTS="--without-lmdb $OPTS"

before_script:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck'

script:
  - ./build.sh
  - ./configure $OPTS
  - make
  - make check
  - make check-static



