dist: trusty
sudo: false

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - OPTS="--enable-parser-generation $OPTS"
  - OPTS="--without-curl $OPTS"
  - OPTS="--without-yajl $OPTS"
  - OPTS="--without-geoip $OPTS"
  - OPTS="--without-lmdb $OPTS"


script:
  - ./build.sh
  - ./configure $OPTS
  - make
  - make check



