dist: trusty
sudo: false

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev

language: cpp

compiler:
  - clang
  - gcc

env:
  - OPTS="--enable-parser-generation"
  - OPTS="--without-curl"


script:
  - ./build.sh
  - ./configure $OPTS
  - make
  - make check



